#!/usr/bin/env python3
"""Generate Sources/FuzzyBar/ZoneLocations.swift from a tzdata release.

Sunrise and sunset need a location, and FuzzyBar has no location access (no
entitlement, no prompt). Every tz database zone has a reference city with
coordinates, so the time zone the Mac is already set to gives a location
that is close enough for a fuzzy clock. The table is baked into the app
rather than read at run time so the sandbox and the OS version don't matter.

Two files from the same release: zone.tab for the cities, and backward for
the old and merged names (US/Eastern, America/Montreal, Asia/Calcutta) that
Foundation still reports as-is. macOS ships zone.tab but not backward, so
take both from IANA:

    curl -LO https://data.iana.org/time-zones/tzdata-latest.tar.gz
    mkdir tzdata && tar -xzf tzdata-latest.tar.gz -C tzdata
    python3 Tools/make_zone_locations.py tzdata
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "Sources/FuzzyBar/ZoneLocations.swift"


def degrees(text):
    """'+4230' / '-0734' / '+404251' / '-0740023' -> signed decimal degrees."""
    m = re.fullmatch(r"([+-])(\d+)", text)
    sign, digits = m.group(1), m.group(2)
    # Degrees are 2 digits for latitude, 3 for longitude; then MM or MMSS.
    deg_len = 2 if len(digits) in (4, 6) else 3
    d, rest = int(digits[:deg_len]), digits[deg_len:]
    value = d + int(rest[:2]) / 60 + (int(rest[2:]) / 3600 if len(rest) > 2 else 0)
    return -value if sign == "-" else value


def parse_zone_tab(path):
    rows = {}
    for line in Path(path).read_text().splitlines():
        if not line or line.startswith("#"):
            continue
        _, coords, zone = line.split("\t")[:3]
        m = re.fullmatch(r"([+-]\d+)([+-]\d+)", coords)
        rows[zone] = (degrees(m.group(1)), degrees(m.group(2)))
    return rows


def parse_links(path):
    """LINK-NAME -> target. A '#= TARGET1' comment names the zone the link
    would point at if the data could link to links (Iceland #= Reykjavik
    rather than Abidjan, which it shares rules with); prefer that."""
    links = {}
    for line in Path(path).read_text().splitlines():
        m = re.match(r"Link\s+(\S+)\s+(\S+)(?:\s+#=\s*(\S+))?", line)
        if m:
            target, name, preferred = m.groups()
            links[name] = preferred or target
    return links


def resolve(name, links, zones):
    seen = set()
    while name not in zones and name in links and name not in seen:
        seen.add(name)
        name = links[name]
    return name if name in zones else None


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    tzdata = Path(sys.argv[1])
    version = (tzdata / "version").read_text().strip()
    zones = parse_zone_tab(tzdata / "zone.tab")
    links = parse_links(tzdata / "backward")
    aliases = {name: city for name in links if name not in zones
               for city in [resolve(name, links, zones)] if city}

    lines = [
        f"// Generated by Tools/make_zone_locations.py from tzdata {version}. Do not edit.",
        "",
        "/// Reference-city coordinates for each tz database zone, and the old or",
        "/// merged names that point at one.",
        "enum ZoneLocations {",
        "    static let table: [String: (latitude: Double, longitude: Double)] = [",
    ]
    lines += [f'        "{z}": ({lat:.4f}, {lon:.4f}),' for z, (lat, lon) in sorted(zones.items())]
    lines += ["    ]", "", "    static let aliases: [String: String] = ["]
    lines += [f'        "{a}": "{z}",' for a, z in sorted(aliases.items())]
    lines += ["    ]", "}", ""]
    OUT.write_text("\n".join(lines))
    print(f"wrote {len(zones)} zones and {len(aliases)} aliases (tzdata {version}) to {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
