#!/usr/bin/env python3
"""Generate Sources/FuzzyBar/ZoneLocations.swift from the system zone.tab.

Sunrise and sunset need a location, and FuzzyBar has no location access (no
entitlement, no prompt). Every tz database zone has a reference city with
coordinates, so the time zone the Mac is already set to gives a location
that is close enough for a fuzzy clock. The table is baked into the app
rather than read at run time so the sandbox and the OS version don't matter.

    python3 Tools/make_zone_locations.py [path/to/zone.tab]
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "Sources/FuzzyBar/ZoneLocations.swift"


def degrees(text):
    """'+4230' / '-0734' / '+404251' / '-0740023' -> signed decimal degrees."""
    m = re.fullmatch(r"([+-])(\d+)", text)
    sign, digits = m.group(1), m.group(2)
    # Degrees are 2 digits for latitude, 3 for longitude; then MM or MMSS.
    deg_len = 2 if len(digits) in (4, 6) else 3
    d, rest = int(digits[:deg_len]), digits[deg_len:]
    value = d + int(rest[:2]) / 60 + (int(rest[2:]) / 3600 if len(rest) > 2 else 0)
    return -value if sign == "-" else value


def parse(path):
    rows = []
    for line in Path(path).read_text().splitlines():
        if not line or line.startswith("#"):
            continue
        _, coords, zone = line.split("\t")[:3]
        m = re.fullmatch(r"([+-]\d+)([+-]\d+)", coords)
        rows.append((zone, degrees(m.group(1)), degrees(m.group(2))))
    return sorted(rows)


def main():
    source = sys.argv[1] if len(sys.argv) > 1 else "/usr/share/zoneinfo/zone.tab"
    rows = parse(source)
    lines = [
        "// Generated by Tools/make_zone_locations.py from zone.tab. Do not edit.",
        "",
        "/// Reference-city coordinates (latitude, longitude) for each tz database zone.",
        "enum ZoneLocations {",
        "    static let table: [String: (latitude: Double, longitude: Double)] = [",
    ]
    lines += [f'        "{zone}": ({lat:.4f}, {lon:.4f}),' for zone, lat, lon in rows]
    lines += ["    ]", "}", ""]
    OUT.write_text("\n".join(lines))
    print(f"wrote {len(rows)} zones to {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
